plugin: gcp_compute
projects:
  - infra-253311
zones:
  - europe-west1-b
groups:
  app: "'app-prod' in name"
  db: "'db-prod' in name"
filters: []
auth_kind: serviceaccount
service_account_file: "/home/vlad/.gcp/infra-253311-496a801da892.json"
hostnames:
  - name
compose:
  ip: networkInterfaces[0].networkIP
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
