---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/vlad/db_config
    owner: vlad
    group: vlad
- copy: 
    src=puma.service
    dest=/etc/systemd/system/puma.service
  notify: reload puma
