- name: App configuration
  hosts: app
  become: true
  vars:
    db_host: 10.132.15.213
  tasks:
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/vlad/db_config
        owner: vlad
        group: vlad
    - copy: src=files/puma.service dest=/etc/systemd/system/puma.service
      notify: reload puma
  handlers:
    - name: reload puma
      systemd: name=puma state=reloaded
